# --- !Ups

-- Insert treatments
INSERT INTO treatment (`Name`,`Cost`) VALUES ('montes Integer Donec',1734.09);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('penatibus taciti metus',702.50);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('aptent nunc Mauris',1985.15);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('aliquam In semper',2590.80);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('conubia id pellentesque',567.33);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('nunc Mauris pede',596.85);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('metus vitae quis',6271.49);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('laoreet Fusce Aenean',8802.36);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('tempus sodales Aenean',3307.64);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('scelerisque blandit netus',8519.33);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('cursus consectetuer erat',7721.33);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('per tellus enim',1795.46);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('vel sapien sociis',7232.86);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('Proin Praesent est',446.52);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('feugiat Nullam suscipit',2872.80);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('nisl nascetur sem',8358.57);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('suscipit et Quisque',6382.00);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('ultricies vehicula Nullam',2924.59);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('auctor Cum a',4500.53);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('ante non adipiscing',6772.39);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('malesuada gravida feugiat',823.89);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('Morbi posuere rutrum',3157.57);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('aliquet elementum convallis',4923.06);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('Pellentesque suscipit condimentum',9744.96);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('sollicitudin est Donec',6458.50);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('condimentum varius vel',7551.98);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('eu tortor dapibus',6670.21);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('Cum hendrerit mattis',7976.23);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('nec sodales convallis',8169.94);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('mattis Vivamus magna',4917.30);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('vestibulum Nunc suscipit',729.38);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('tempor leo leo',1769.93);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('gravida augue suscipit',7302.24);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('condimentum magnis ante',3720.78);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('id vulputate sed',3437.31);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('dolor sollicitudin Donec',7623.77);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('tincidunt vestibulum faucibus',9319.06);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('inceptos at Class',5183.47);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('aliquet turpis lacinia',4010.28);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('accumsan nulla aptent',8546.97);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('mi a posuere',2777.33);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('arcu suscipit Class',6744.70);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('Praesent risus magnis',2297.43);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('hendrerit Sed Proin',9333.15);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('convallis consequat convallis',7042.59);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('tempor pretium mattis',1319.92);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('quam suscipit pharetra',9887.99);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('aptent adipiscing neque',4977.82);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('luctus ultrices mollis',5578.59);
INSERT INTO treatment (`Name`,`Cost`) VALUES ('dictum vel Fusce',5339.67);

-- Insert locations
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,3,6,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,9,6,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,9,10,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,8,4,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,45,8,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,9,10,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,90,5,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,26,1,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,89,2,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,22,3,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,43,2,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,86,1,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,89,10,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,3,6,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (3,47,3,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (6,39,3,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,18,9,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,52,10,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,25,9,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,7,9,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,19,1,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,32,4,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,60,5,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,9,10,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,96,1,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,62,7,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,26,5,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,52,8,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,50,2,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,58,7,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,6,3,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,51,1,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,1,7,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (2,17,7,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,59,4,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (2,85,6,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,90,5,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,45,2,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,82,10,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,8,1,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (3,80,8,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,54,5,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,11,1,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (3,90,9,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (3,47,5,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,84,6,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (6,45,1,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (2,91,4,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,60,3,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (2,18,1,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,78,9,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (2,78,2,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (6,57,10,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,48,5,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,90,6,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,5,6,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (3,8,3,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (6,83,1,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (2,41,8,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,9,4,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,58,10,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,5,1,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,90,9,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (3,31,2,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,97,1,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,6,1,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,45,8,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,58,9,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (6,81,10,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,93,7,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (2,68,9,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,4,10,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,74,6,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,82,3,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (3,73,7,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,96,7,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (3,29,4,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (3,73,10,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,50,10,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,61,10,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,81,2,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,43,6,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,46,5,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,91,9,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,67,7,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,72,8,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (7,76,6,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (6,9,5,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (3,21,4,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,11,1,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (5,69,7,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,65,1,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,41,3,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,11,3,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (8,76,1,3);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,79,6,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,15,10,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (6,68,5,1);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (1,25,3,2);
INSERT INTO location (`Floor`,`Room`,`BedCount`,`Unit_ID`) VALUES (4,68,1,1);

-- Insert Patients
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Valenzuela','Amethyst','018-218-7546','78091 West Comoros Way','gI5nFkpK');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Mcneil','David','147-186-5257','73549 South Allentown Way','o328lZLM');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Sanders','Madaline','150-779-2587','35323 North Netherlands Antilles Blvd.','U4QfSnTp');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Robbins','Phelan','009-229-4617','4585  Pakistan St.','Wm6rihkx');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Rodriguez','Celeste','575-539-0012','6225 West Malawi Ln.','yQmSiqL8');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Hampton','Tana','447-977-8206','95194 North Bouvet Island Way','QMtBk7G0');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Gillespie','Aaron','515-218-9670','5738 North Bangladesh Way','uMouSuI3');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Odonnell','Noble','109-192-6826','56020 North Cyprus Blvd.','7fpYf9g0');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Noel','Rooney','708-487-8221','16342 South Columbus Ave.','mzdu989Q');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Doyle','Judith','491-293-8618','46319 North United Arab Emirates Way','2sQ5s0cA');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Burt','Benedict','042-826-0230','46183 West Gabon St.','FDwbQ3ZE');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Bowers','Libby','480-803-0278','74816 North Dubuque Way','YEQdvXZn');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Hancock','Shelby','681-204-8919','45673 East Bosnia and Herzegovina Blvd.','fTEHdp9l');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Delgado','Portia','838-990-4474','11834  Viet Nam Ln.','ayoj64ln');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Webb','Yen','049-662-1473','65217 West Hong Kong Ave.','7E3vKJwf');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Potts','Graiden','261-747-3353','65728 East Northern Mariana Islands Way','v1MnBx8k');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Mayo','Stacy','242-632-4135','97583 North Carrollton Ln.','8irsskkr');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Duncan','Nasim','260-935-9071','73130 East Congo Way','KKZCgY4y');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Rollins','Aladdin','111-747-3400','49972 West Australia Ct.','49fVz9WW');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Moore','Ciaran','479-252-4743','63706 South Chad St.','X7FaNPfy');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Stark','Clementine','749-066-6169','84388 West Saint Lucia Blvd.','uof0Ac6B');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Bates','Lucius','095-716-6130','33461  Ghana St.','EsudfQ1f');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Reid','Quinn','259-902-1815','11687 South Bremerton Way','J3wCuni0');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Irwin','Abel','960-798-5370','52455  Hoboken Ln.','QJHvxE3d');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Watson','Mark','855-746-4141','63462 South Mexico Way','gLNKr5Ad');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Roy','Destiny','567-878-4015','17324 East Guam Ave.','CLuGxJvR');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Roth','Maia','634-708-3902','54565  Bosnia and Herzegovina Ct.','hQXXTKN7');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Higgins','Jared','978-637-4193','24678  Namibia Blvd.','siW4fy2w');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Baldwin','Tarik','325-289-8728','21520 West Bangladesh Ave.','S0NzYnZE');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Swanson','Uriah','494-640-7812','59682 East Hilo Ct.','4C5iEzRu');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Copeland','Levi','808-780-3721','65711  Moldova Ave.','klqL3I4g');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Harrington','Yen','603-122-4930','42722 East Poland Ct.','bG5dtJ3p');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Goodwin','Wang','701-432-0090','76739 North Germany Ln.','rjVQoFQ2');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Lott','Quemby','122-044-0388','56312 East Eritrea Way','8gA2dzkC');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Kirby','Wesley','233-749-7303','94338 West Davenport St.','GCF6YLPf');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Lynn','Paul','171-674-8428','88517 South Congo Ct.','56pTpGpF');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Craig','Griffin','122-523-7777','67515  Compton Ln.','phC2RzbL');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Ray','Harper','576-143-6269','10403  Korea St.','0rA1FiAK');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Knowles','Eve','515-121-3570','24001 North Tajikistan St.','J0U8pCp7');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Smith','Cora','129-616-7430','76292  China St.','yKED4iiJ');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Odonnell','Porter','574-315-4970','35629 South Norfolk Island Way','CtSTuakq');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Powell','Tashya','941-439-4949','78208 North Czech Republic Blvd.','KDm7VqLa');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Mcintosh','Libby','800-370-0933','18861 West Botswana Ct.','2l36EIp6');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Rojas','Paki','684-141-3912','74692 South Angola St.','fnypF2sv');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Mcmillan','MacKenzie','353-445-3894','66975 South Guam Ct.','uwStJDe6');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Reilly','Edan','720-552-2789','45716 South Elkhart Ln.','LPqQA57G');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Brady','Chanda','380-066-0814','70096  Australia Ln.','vKNroxWm');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Farrell','Robin','596-577-7833','93505 East Duncan Way','Z0eRZdhC');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Mcclain','Moses','892-397-2641','17930 North Cameroon Blvd.','q9upEcUc');
INSERT INTO patient (`Last_Name`,`First_Name`,`Phone_Number`,`Address`,`Medicare_Number`) VALUES ('Short','Kane','202-307-4458','60712 South Saint Helena Ave.','12Rs86t2');

-- Insert treatment instances
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-03-10',2,11,41,75);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-10-23',34,37,3,96);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-11',9,25,34,74);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-15',40,7,20,2);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-23',45,5,19,78);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-03-12',9,14,1,44);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-06-02',32,25,32,10);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-09-11',22,28,35,66);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-09-11',45,23,19,86);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-06-17',50,4,12,53);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-05-11',46,13,43,40);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-12-29',35,21,18,7);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-12-19',35,38,1,47);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-04-10',41,24,1,91);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-09',4,34,30,87);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-07-24',12,50,49,83);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-11-26',5,34,9,88);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-15',23,37,26,46);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-09-26',8,24,13,83);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-07-05',8,1,22,40);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-09-16',40,10,10,80);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-05-11',23,13,38,6);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-04-19',4,25,34,19);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-05-20',14,20,42,68);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-06-05',45,23,32,39);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-11-17',33,42,38,51);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-19',45,38,37,97);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-07-29',28,28,12,60);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-08-16',43,32,47,18);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-10-31',35,4,18,23);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-04-17',48,7,44,83);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-03-24',14,32,18,50);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-21',42,32,45,56);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-03-10',4,14,48,69);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-08-09',43,10,29,32);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-07-19',17,38,14,81);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-26',29,49,2,100);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-03-31',11,45,34,39);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-01',12,49,39,3);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-07-08',41,28,6,84);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-10',46,20,25,49);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-09-14',25,26,1,92);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-12-06',27,33,29,22);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-05-24',49,4,8,58);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-08-30',24,16,44,99);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-12-15',23,43,36,5);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-04-26',5,10,16,43);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-09-10',35,33,38,65);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-09-18',41,42,15,95);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-03-11',34,10,14,41);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-07-25',9,16,46,64);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-12-03',34,37,11,3);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-05-09',43,1,45,54);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-06',43,38,43,42);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-09-01',39,25,7,78);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-28',26,34,7,41);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-23',14,26,44,96);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-12-27',35,18,45,70);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-04-11',19,4,38,84);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-29',49,12,46,96);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-05-27',31,42,13,29);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-06-16',32,12,45,83);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-03',46,40,1,38);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-05-04',16,7,38,76);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-08-22',45,43,23,17);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-19',4,48,41,68);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-03-14',25,41,41,100);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-04-16',4,34,1,23);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-12-15',24,50,50,1);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-10-20',42,43,13,8);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-06-21',43,15,26,27);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-04-30',15,15,28,46);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-05-21',25,2,46,13);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-22',50,7,25,41);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-11-14',21,4,4,32);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-17',44,2,20,58);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-07-05',16,45,1,25);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-10-30',11,44,27,95);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-06-13',18,43,12,30);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-09',18,13,13,83);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-25',16,37,24,78);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-05',35,43,8,84);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-04-11',49,44,31,47);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-06-14',12,3,48,37);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-08-27',36,16,24,20);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-08-19',19,7,35,71);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-08-14',22,46,43,78);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-28',45,9,40,37);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-12-08',12,19,16,53);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-05-28',25,28,6,74);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-06-18',45,50,12,32);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-05-04',13,39,39,75);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-08-16',42,40,20,35);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-01-25',30,22,25,51);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-09-11',33,15,37,88);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-06-17',5,29,28,4);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-14',48,25,25,98);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-12-15',10,23,45,98);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2014-08-21',48,6,43,99);
INSERT INTO `treatment_instances` (`Treatment_Date`,`Patient_ID`,`Employee_ID`,`Treatment_ID`,`Location_ID`) VALUES ('2015-02-03',45,25,3,8);


# --- !Downs
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM treatment;
DELETE FROM location;
DELETE FROM patient;
DELETE FROM treatment_instances;
SET FOREIGN_KEY_CHECKS = 1;

